name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check_backend:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.18'
      - name: Install dependencies
        run: npm install
      - name: Build common module
        run: npm run build:common
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
  check_frontend:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.18'
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
  deploy_app:
    runs-on: ubuntu-20.04
    needs: [check_backend, check_frontend]
    steps:
      - name: Deploy to render
        if: ${{ github.event_name == 'push' }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
